Shizuru Font: Version 1.000 added
google/fonts pull request #2871
Opened 2020-12-09 03:47 UTC by aaronbell

690f52e: [gftools-packager] Shizuru Font: Version 1.000 added

* Shizuru Font Version 1.000 taken from the upstream repo https://github.com/shibuyafont/shizuru-font.git at commit https://github.com/shibuyafont/shizuru-font/commit/a03af0c110a8ac65c79fdb1b67df89cd5cfffda8.

 4c8cf76: [gftools-packager] ofl/shizurufont remove METADATA "source".  google/fonts#2587

2021-04-08 15:24 UTC, RosaWagner commented on ofl/shizurufont/DESCRIPTION.en_us.html
> +    About Lineup of Shibuya font
This line to remove

2021-04-08 15:25 UTC, RosaWagner commented
"font" to remove from the name.

2021-04-13 23:25 UTC, aaronbell commented on ofl/shizurufont/DESCRIPTION.en_us.html
> +    About Lineup of Shibuya font
Done

2021-04-19 19:03 UTC, aaronbell commented
Will update PR once new descriptions are ready.

2021-05-01 08:45 UTC, mintoming commented
New description here:

This is a font based on the handwritten sketch by handicapped artists, refined & created by design major students. The unique lines create its exceptional atmosphere. This is one of the work of Shibuya Font project, a collaboration of design major students and handicapped artist living in Shibuya city, officially approved by Shibuya city in Tokyo. 
http://www.shibuyafont.jp

2021-05-07 20:38 UTC, aaronbell commented
@m4rc1e Ready for review

2021-05-14 11:32 UTC, m4rc1e commented
please rename the dir to "shizuru"

2021-05-14 11:33 UTC, m4rc1e requested changes
Please rename the dir to shizuru

2021-05-14 15:42 UTC, aaronbell commented
@m4rc1e Done!

2021-06-15 01:40 UTC, davelab6 commented
@m4rc1e can this be merged?

2021-07-15 13:13 UTC, merged