IBM Plex Sans: Version 3.2 added
google/fonts pull request #3439
Opened 2021-05-21 10:31 UTC by yanone

7170e18: [gftools-packager] IBM Plex Sans: Version 3.2 added

* IBM Plex Sans Version 3.2 taken from the upstream repo https://github.com/googlefonts/plex at commit https://github.com/googlefonts/plex/commit/f7e3f72d1473413031e61680b3353c5f9241da8c.

 8a3351d: [gftools-packager] ofl/ibmplexsans remove METADATA "source".  google/fonts#2587

2021-05-21 11:37 UTC, yanone commented
All visible FAILs are intentionally left in place:
* Vertical metrics (checked for regression)
* Copyright strings left untouched
* Hinting-related: `fix-nonhinting` (as suggested in the FAIL) messed up the manual hinting.

Basically, I just went over the name table.

2021-06-02 13:35 UTC, RosaWagner commented
Report was too long to be posted here, I removed Thin, ThinItalic, SemiBold, SemiBold Italic from it.

## Fontbakery report

Fontbakery version: 0.7.37

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Fonts have consistent underline thickness?</summary>

* [com.google.fonts/check/family/underline_thickness](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/post.html#com.google.fonts/check/family/underline_thickness)
<pre>--- Rationale ---
Dave C Lemon (Adobe Type Team) recommends setting the underline thickness to be
consistent across the family.
If thicknesses are not family consistent, words set on the same line which have
different styles look strange.
See also:
https://twitter.com/typenerd1/status/690361887926697986</pre>

* 🔥 **FAIL** Thickness of the underline is not the same across this family. In order to fix this, please make sure that the underlineThickness value is the same in the 'post' table of all of this family font files.
Detected underlineThickness values are:
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-Bold.ttf: 100
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-BoldItalic.ttf: 100
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-ExtraLight.ttf: 26
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-ExtraLightItalic.ttf: 26
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-Italic.ttf: 60
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-Light.ttf: 43
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-LightItalic.ttf: 43
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-Medium.ttf: 77
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-MediumItalic.ttf: 77
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-Regular.ttf: 60
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-SemiBold.ttf: 88
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-SemiBoldItalic.ttf: 88
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-Thin.ttf: 16
	/Users/rosalie/Desktop/QA/fonts/ofl/ibmplexsans/IBMPlexSans-ThinItalic.ttf: 16
 [code: inconsistent-underline-thickness]

</details>
<br>
</details>
<details>
<summary><b>[21] IBMPlexSans-Bold.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file contain a upstream Git repo URL?</summary>

* [com.google.fonts/check/description/git_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/git_url)
<pre>--- Rationale ---
The contents of the DESCRIPTION.en-us.html file are displayed on the Google
Fonts website in the about section of each font family specimen page.
Since all of the Google Fonts collection is composed of libre-licensed fonts,
this check enforces a policy that there must be a hypertext link in that page
directing users to the repository where the font project files are made
available.
Such hosting is typically done on sites like Github, Gitlab, GNU Savannah or any
other git-based version control service.</pre>

* 🔥 **FAIL** Please host your font project on a public Git repo (such as GitHub or GitLab) and place a link in the DESCRIPTION.en_us.html file. [code: lacks-git-url]

</details>
<details>
<summary>🔥 <b>FAIL:</b> DESCRIPTION.en_us.html must have less than 1000 bytes.</summary>

* [com.google.fonts/check/description/max_length](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/max_length)

* 🔥 **FAIL** DESCRIPTION.en_us.html must have size smaller than 1000 bytes. [code: too-long]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check license file has good copyright string.</summary>

* [com.google.fonts/check/license/OFL_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_copyright)
<pre>--- Rationale ---
An OFL.txt file&#x27;s first line should be the font copyright e.g:
&quot;Copyright 2019 The Montserrat Project Authors
(https://github.com/julietaula/montserrat)&quot;</pre>

* 🔥 **FAIL** First line in license file does not match expected format: "copyright © 2017 ibm corp. with reserved font name "plex""

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in METADATA.pb</summary>

* [com.google.fonts/check/metadata/valid_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_copyright)
<pre>--- Rationale ---
The expected pattern for the copyright string adheres to the following rules:
* It must say &quot;Copyright&quot; followed by a 4 digit year (optionally followed by a
hyphen and another 4 digit year)
* Then it must say &quot;The &lt;familyname&gt; Project Authors&quot;
* And within parentheses, a URL for a git repository must be provided
* The check is case insensitive and does not validate whether the familyname is
correct, even though we&#x27;d expect it is (and we may soon update the check to
validate that aspect as well!)
Here is an example of a valid copyright string:
&quot;Copyright 2017 The Archivo Black Project Authors
(https://github.com/Omnibus-Type/ArchivoBlack)&quot;</pre>

* 🔥 **FAIL** METADATA.pb: Copyright notices should match a pattern similar to:
 "Copyright 2020 The Familyname Project Authors (git url)"
But instead we have got:
"copyright 2018 ibm corp. all rights reserved." [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)

* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright 2018 IBM Corp. All rights reserved." [code: bad-notice-format]
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright 2018 IBM Corp. All rights reserved." [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions?</summary>

* [com.google.fonts/check/smart_dropout](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/smart_dropout)
<pre>--- Rationale ---
This setup is meant to ensure consistent rendering quality for fonts across all
devices (with different rendering/hinting capabilities).
Below is the snippet of instructions we expect to see in the fonts:
B8 01 FF    PUSHW 0x01FF
85          SCANCTRL (unconditinally turn on
                      dropout control mode)
B0 04       PUSHB 0x04
8D          SCANTYPE (enable smart dropout control)
&quot;Smart dropout control&quot; means activating rules 1, 2 and 5:
Rule 1: If a pixel&#x27;s center falls within the glyph outline,
        that pixel is turned on.
Rule 2: If a contour falls exactly on a pixel&#x27;s center,
        that pixel is turned on.
Rule 5: If a scan line between two adjacent pixel centers
        (either vertical or horizontal) is intersected
        by both an on-Transition contour and an off-Transition
        contour and neither of the pixels was already turned on
        by rules 1 and 2, turn on the pixel which is closer to
        the midpoint between the on-Transition contour and
        off-Transition contour. This is &quot;Smart&quot; dropout control.
For more detailed info (such as other rules not enabled in this snippet), please
refer to the TrueType Instruction Set documentation.</pre>

* 🔥 **FAIL** The 'prep' table does not contain TrueType instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the `gfto [...]

2021-06-03 06:14 UTC, yanone commented
So the above FAILs were essentially all accepted by either Marc or Dave, either in writing or during the call. I asked Marc to take a look at the naming table of the Condensed, which I did change according to our specs, and this is still pending. 

Otherwise, I looked at all the FAILs and decided to let them go, since they are professionally produced fonts. What's essential to Marc and Dave is that the vertical metrics stay intact visually, and they do, and that the family stays intact as far as missing fonts go.

In my opinion, we just need to pay special attention to the naming. The fonts which are live now already don't follow our naming specs (I think this may be true only for the Condensed), so it could be argued to either leave them as they are, in which case I would roll back my entire line of changes and we just publish the original fonts as they are, or we choose to follow our specs, in which case the fonts from my PR should be shipped.

2021-06-09 11:40 UTC, m4rc1e requested changes
> Basically, I just went over the name table.

I'm worried that the postscript name has been modified which will affect some applications. Personally, I'd just keep the same name table as the old fonts. Apologies i didn't tell you this in advance.

Everything else looks great!

2021-06-10 13:28 UTC, yanone commented
Updated

## IBM Plex Sans: Version 3.2 added

---
 2732c87: [gftools-packager] IBM Plex Sans: Version 3.2 added

* IBM Plex Sans Version 3.2 taken from the upstream repo https://github.com/googlefonts/plex at commit https://github.com/googlefonts/plex/commit/5489e99859e9b4a88faf3013324d89a34a294c53.

 6024189: [gftools-packager] ofl/ibmplexsans remove METADATA "source".  google/fonts#2587

2021-06-10 13:29 UTC, yanone commented
I updated the name tables. This is ready for review now.

2021-06-11 11:10 UTC, yanone commented
Updated

## IBM Plex Sans: Version 3.2 added

---
 a9ddc06: [gftools-packager] IBM Plex Sans: Version 3.2 added

* IBM Plex Sans Version 3.2 taken from the upstream repo https://github.com/googlefonts/plex at commit https://github.com/googlefonts/plex/commit/71d012bccb31a2e282cc46de63b387ff7f676287.

 b889ba6: [gftools-packager] ofl/ibmplexsans remove METADATA "source".  google/fonts#2587

2021-06-23 16:51 UTC, merged