Remove "free" from font family descriptions
google/fonts pull request #4444
Opened 2022-03-30 16:36 UTC by davelab6

This is an urgent set of changes to family descriptions, requested by an internal stakeholder.

@RosaWagner this will require a large set of families to be added `to_sandbox.txt`

2022-03-30 17:07 UTC, davelab6 commented
The git diff isn't super clean due to this touching a lot of files that haven't been touched in many many years, so I'm going to follow up with a 2nd commit on this branch with minor fixes to make diffing cleaner.

2022-03-31 08:26 UTC, davelab6 commented
OK this is now ready for review by internal stakeholders, I'll comment (or merge) when ready

I've also just added a 2nd commit to add the relevant families `to_sandbox.txt`, which I found with

    git diff-tree --no-commit-id --name-only -r  COMMIT

and then processed with 

    cut -d/ -f1,2

2022-03-31 21:25 UTC, RosaWagner commented
@davelab6 i don’t think it is a good idea, we generate the lists with a script once a week to avoid conflict with the eng team, and the idea is to have this task automated thanks to the script, manual changes to the lists is messing up the checking workflow. If we all change the lists at the same time, we lose track of stuff, better to wait for one push to be finished before adding new stuff.

If you add the PR to traffic Jam with the labels:
- To sandbox
- desc/Metadata/license

then you can generate the whole sandbox list with `gftools gen-push-lists` script.

2022-08-20 13:38 UTC, chrissimpkins commented
Rebased on main and took Dave's changes on all DESCRIPTION files, main side on all to_sandbox.txt files.  There are no diffs on to_sandbox.txt in this branch now.  Should be ready for review and merge.

2022-08-20 13:41 UTC, chrissimpkins commented
> OK this is now ready for review by internal stakeholders, I'll comment (or merge) when ready

@davelab6 Waiting on this OK from you to merge

2022-09-09 00:06 UTC, chrissimpkins commented
@davelab6 Are we ready to merge these changes?

2022-09-11 23:38 UTC, vv-monsalve requested changes

2022-09-11 23:38 UTC, vv-monsalve commented on ofl/dawningofanewday/DESCRIPTION.en_us.html
> +They like to think of each new day as a chance to start fresh, without past mistakes.
Suggestion looking for pronouns consistency based on original version:

The title was chosen by the designer's friend but also had great meaning to the author as she likes to think of each new day as a chance to start fresh, without past mistakes.

2022-09-11 23:38 UTC, vv-monsalve commented on ofl/niconne/DESCRIPTION.en_us.html
> +Nicone has been redesigned and shaped to create a new version of the 1925 typeface that can now be across across the internet by web browsers on desktop computers, laptops and mobile devices.
that can now be **used** across the etc…

2022-09-11 23:38 UTC, vv-monsalve commented on ofl/portersansblock/DESCRIPTION.en_us.html
> +Porter Sans Block is a style of Porter Sans.
Didn't find this font in the catalog

2022-09-11 23:38 UTC, vv-monsalve commented on ofl/meerainimai/DESCRIPTION.en_us.html
>  The Meera Inimai project is led by Swathanthra Malayalam Computing, a free software community in Kerala, India.
libre software community

2025-01-15 15:49 UTC, chrissimpkins commented
We have numerous merge conflicts on this PR now. Will need to rebase changes on main and revise the wording again in order to land this.  Closing this PR.

2025-01-15 15:49 UTC, closed without merging