Noto Sans Balinese: Version 2.004 added
google/fonts pull request #5758
Opened 2023-01-10 14:02 UTC by simoncozens

387ff1f: [gftools-packager] Noto Sans Balinese: Version 2.004 added

* Noto Sans Balinese Version 2.004 taken from the upstream repo https://github.com/notofonts/balinese.git at commit https://github.com/notofonts/balinese/commit/.

2023-01-16 17:53 UTC, m4rc1e requested changes
Collisions have been introduced when I check the text preview. 

Old:
<img width="321" alt="Screenshot 2023-01-16 at 17 51 35" src="https://user-images.githubusercontent.com/7525512/212740088-86818192-7395-44f3-866c-bbe5f8c34017.png">


New:
<img width="294" alt="Screenshot 2023-01-16 at 17 51 42" src="https://user-images.githubusercontent.com/7525512/212740042-89384857-4b8f-4b54-bcaa-49cb392b55f2.png">

2023-03-29 10:09 UTC, RosaWagner commented on ofl/notosansbalinese/METADATA.pb
>  languages: "ban_Bali"  # Balinese, Balinese
also missing primary script

2024-02-13 17:09 UTC, simoncozens commented
Updated

## Noto Sans Balinese: Version 2.005 added

---
 e58193b: [gftools-packager] Noto Sans Balinese: Version 2.005 added

* Noto Sans Balinese Version 2.005 taken from the upstream repo https://github.com/notofonts/balinese.git at commit https://github.com/notofonts/balinese/commit/.

2024-02-13 17:15 UTC, simoncozens commented
```
Noto Sans Balinese v2.005

This release:
* Fixes many third-level stacking conjuncts (#3)
* Fixes several other conjunct issues (#4)
* Monospaces the musical symbols (#6)
* Improves the rendering of -u/-uu after conjuncts (#10)
* Improves the positioning of anchors on a dotted circles (#16)
* Fixes a number of overlaps (#33)
* Removes hinting from non-hinted builds (#37)
```

2024-04-10 17:51 UTC, vv-monsalve commented
> 🔥 FAIL Please remove 'cyrillic-ext' from METADATA.pb since none of its glyphs are supported by this font file. [code: unsupported-subset]

Please confirm if we can delete these subsites.

2024-04-10 18:06 UTC, vv-monsalve commented
- There are now some issues kerning and diacritics regresions in the latin companion
    ![NotoSansBalinese-Latin](https://github.com/google/fonts/assets/48698976/20453731-108d-49ca-9fb7-9e123a2c86ea)

- Could you please confirm about these collisions?
    
<img width="407" alt="Screen Shot 2024-04-10 at 12 54 50" src="https://github.com/google/fonts/assets/48698976/276da0a4-de31-4ceb-98f2-e5536f5fa20e">

2024-05-15 15:31 UTC, simoncozens commented
These are actually all fine but I have 2.006 coming out soon anyway...

2024-05-15 15:31 UTC, closed without merging