Noto Sans: Version 2.010 added
google/fonts pull request #5789
Opened 2023-01-17 14:20 UTC by simoncozens

fc37d2d: [gftools-packager] Noto Sans: Version 2.010 added

* Noto Sans Version 2.010 taken from the upstream repo https://github.com/notofonts/latin-greek-cyrillic.git at commit https://github.com/notofonts/latin-greek-cyrillic/commit/.

2023-01-18 15:53 UTC, m4rc1e commented
On first glance it looks like the Devanagari has lost its GPOS and GSUB lookups. Marks are not positioned well and conjuncts are not forming. Everything else looks ok. There are some missing glyphs but I don't know how serious this is.

2023-03-29 12:03 UTC, simoncozens commented
Updated

## Noto Sans: Version 2.011 added

---
 57512b9: [gftools-packager] Noto Sans: Version 2.011 added

* Noto Sans Version 2.011 taken from the upstream repo https://github.com/notofonts/latin-greek-cyrillic.git at commit https://github.com/notofonts/latin-greek-cyrillic/commit/.

2023-03-29 15:20 UTC, simoncozens commented
Expected changes from previous release:

```
This release:
* Fixes a layout issue with the embedded Devanagari subset in the Google Fonts builds
* Fixes soft-dotting of i and j glyphs with accents (#64, thanks to Denis Jacquerye)
* Improves the position of marks below small capital J (#60)
* Removes the erroneous U+11AB0/11AB1 glyphs (#405)
* Adds slashed pnum/onum zeros (#159)
* Adds the U+10FB GEORGIAN PARAGRAPH SEPARATOR character for medievalists (#37)
* Adds the U+2183 ROMAN NUMERAL REVERSED ONE HUNDRED character (#129)
```

2023-04-13 12:49 UTC, RosaWagner commented
@simoncozens the devanagari is upright in the italic style

And this;
https://user-images.githubusercontent.com/12222436/231763226-f30a234a-3424-45e3-b404-8f0a8318405f.mov

2023-04-18 16:30 UTC, simoncozens commented
> @simoncozens the devanagari is upright in the italic style

We don't have an italic deva, so that's just part of the compromise. 

> And this;
[user-images.githubusercontent.com/12222436/231763226-f30a234a-3424-45e3-b404-8f0a8318405f.mov](https://user-images.githubusercontent.com/12222436/231763226-f30a234a-3424-45e3-b404-8f0a8318405f.mov)

That's not loading for me. :-/

2023-04-20 06:30 UTC, simoncozens commented
I'm happy with the Deva change as well; it's a variable font thing.

2023-05-04 09:28 UTC, simoncozens commented
I'm looking at the glyphsets issues here too. I'll see if we can get the Vedic characters into a Google Fonts release but really I'm not worried about them. They are very rare, and people should use Noto Sans Devanagari if they're going to expect vedic signs to work. But I'll try.

But I have changed my mind about the iMatra lengths. This should work, as it does work in the Noto Sans Devanagari variable font.

2023-05-24 16:16 UTC, simoncozens commented
Updated

## Noto Sans: Version 2.012 added

---
 350c838: [gftools-packager] Noto Sans: Version 2.012 added

* Noto Sans Version 2.012 taken from the upstream repo https://github.com/notofonts/latin-greek-cyrillic.git at commit https://github.com/notofonts/latin-greek-cyrillic/commit/.

2023-05-25 12:50 UTC, RosaWagner commented
@simoncozens do you know what it means? 

🔥 FAIL: Checking with ots-sanitize. ([com.google.fonts/check/ots](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/ots))
🔥 FAIL ots-sanitize returned an error code (1). Output follows:
ERROR: GPOS: Bad mark anchor offset 0 for mark table 63
ERROR: GPOS: Failed to parse mark array
ERROR: Layout: Failed to parse lookup subtable 4
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 33
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
[code: ots-sanitize-error]

2023-05-30 14:30 UTC, m4rc1e requested changes
Hey,

Apologies for the late review.

Devanagari mark positions look broken.

old:

<img width="1317" alt="Screenshot 2023-05-30 at 15 29 15" src="https://github.com/google/fonts/assets/7525512/0a626aae-92b1-4c50-a8c0-1f9d2c7f453a">


new:

<img width="1359" alt="Screenshot 2023-05-30 at 15 28 25" src="https://github.com/google/fonts/assets/7525512/3f4bb478-d21d-4006-a7cf-e7b5827a6069">

Everything else LGTM

2023-06-05 13:09 UTC, m4rc1e reviewed
Deva look much better. Only nit seems to be:


Old:

<img width="171" alt="Screenshot 2023-06-05 at 14 08 17" src="https://github.com/google/fonts/assets/7525512/8b25566e-9cd5-4a15-b993-53d3743c28bd">

new:

<img width="152" alt="Screenshot 2023-06-05 at 14 09 04" src="https://github.com/google/fonts/assets/7525512/87bc8bbb-83ce-4d30-9118-010af20badb2">

Old looks better but this probably isn't a deal breaker.

2023-06-05 19:56 UTC, simoncozens commented
Yeah, I think that's an issue with the Noto Sans Devanagari variable-ification; we lost some of the master-specific positioning adjustments. But we have more major updates to Noto Sans *and* NS Devanagari planned this year, so we'll fix it next release.

2023-06-06 11:05 UTC, m4rc1e approved these changes

2023-06-07 09:56 UTC, merged

2023-10-13 10:25 UTC, simoncozens commented
Wait, did this *not* go to Sandbox? I think it should be able to go now.

2023-10-13 10:32 UTC, RosaWagner commented
It is in Sandbox, but the ots sanitiser problem has impacted other teams, Garret said he is working on pushing it to prod this week or the next