Gilda Display: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
google/fonts pull request #5815
Opened 2023-01-20 14:41 UTC by emmamarichal

80372d6: [gftools-packager] Gilda Display: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added

* Gilda Display Version 1.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/etunni/gilda-display at commit https://github.com/etunni/gilda-display/commit/777747f6e14e91c8676b46461c799d10c3a18c26.

 7c11169: Gilda Display: description updated

2023-01-20 15:07 UTC, m4rc1e requested changes
Germandbls is empty.

<img width="276" alt="Screenshot 2023-01-20 at 15 03 50" src="https://user-images.githubusercontent.com/7525512/213730796-0ec619e9-a890-4228-b942-04b51f0d51a8.png">

It's better to simply not have an empty glyph so fallbacks work correctly, like the old font e.g

<img width="728" alt="Screenshot 2023-01-20 at 15 05 24" src="https://user-images.githubusercontent.com/7525512/213731281-b022e30e-1026-4fee-8665-01b2285fc4d0.png">
old

<img width="699" alt="Screenshot 2023-01-20 at 15 05 56" src="https://user-images.githubusercontent.com/7525512/213731321-9b9eae02-c4e0-4ad6-a307-d70f3af9d8f3.png">

new

2023-01-20 15:09 UTC, emmamarichal commented
Ah yes indeed, I'll change that, thanks!

2023-01-25 13:06 UTC, emmamarichal commented
Updated

## Gilda Display: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.22] added

---
 aacc2d1: [gftools-packager] Gilda Display: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.22] added

* Gilda Display Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.22] taken from the upstream repo https://github.com/etunni/gilda-display at commit https://github.com/etunni/gilda-display/commit/640bdfd3d2ee3b533d1f88687a9e4541136254e0.

 e4ee36a: New push / description updated

2023-01-25 15:50 UTC, m4rc1e approved these changes

2023-01-25 15:50 UTC, merged