Noto Sans Arabic: Version 2.011 added
google/fonts pull request #6859
Opened 2023-10-13 09:28 UTC by simoncozens

3920071: [gftools-packager] Noto Sans Arabic: Version 2.011 added

* Noto Sans Arabic Version 2.011 taken from the upstream repo https://github.com/notofonts/arabic.git at commit https://github.com/notofonts/arabic/commit/.

2023-10-13 09:35 UTC, simoncozens commented
This release:

* Brings codepoint support up to Unicode 14
* Includes extensive re-engineering to fix bugs (particularly in minority languages), reduce glyphset size, and increase consistency with other Noto Arabic families

2023-10-13 12:55 UTC, khaledhosny commented
> Unicode 14

Unicode 15 (there were 3 new Arabic code points added in Unicode 15 that are npw supported as well)
https://www.unicode.org/charts/PDF/Unicode-15.0/

2023-10-31 00:25 UTC, eliheuer commented
@simoncozens There is one FontBakery vertical metrics fail, is there a good reason to ignore this? Or should it be fixed and the PR updated before merging?

🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent. ([com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent))
🔥 FAIL OS/2.usWinAscent value should be equal or greater than 1431, but got 1374 instead [code: ascent]

I looks around in previous PRs, but couldn't find any prior discussion of this.

2023-10-31 01:29 UTC, eliheuer commented
One thing to note for anyone else reviewing this, the change to `ARABIC DISPUTED END OF AYAH` `U+08E2` looks legit to me after some research: https://www.unicode.org/L2/L2014/14095-quranic-marks.pdf

2023-10-31 01:59 UTC, eliheuer commented
There is a regression with Arabic Letter Reh with Stroke `U+075B`

Before:
<img width="115" alt="Screenshot 2023-10-30 at 6 59 14 PM" src="https://github.com/google/fonts/assets/5162664/9cddf03e-e231-4049-ab8a-12a93b28c3a8">
After:
<img width="104" alt="Screenshot 2023-10-30 at 6 59 20 PM" src="https://github.com/google/fonts/assets/5162664/1871de00-8921-4593-808f-1006a53746fe">

2023-10-31 03:35 UTC, eliheuer commented
@simoncozens the Heh`U+0647` ه has been changed to look like an initial Heh ﻫ. I know this is done sometimes for legibility, on my Macbook Arabic keyboard they do this for example, but what is the rational for this?

I have basic Arabic reading skills, and I would find this strange and would expect the circular form without the middle loop when typing `U+0647`

Before:
<img width="128" alt="Screenshot 2023-10-30 at 8 26 38 PM" src="https://github.com/google/fonts/assets/5162664/3d6b00f9-f76e-4806-80fd-bf75f4539b71">
After:
<img width="115" alt="Screenshot 2023-10-30 at 8 26 44 PM" src="https://github.com/google/fonts/assets/5162664/b78f5368-f6de-43a2-a773-72005fd8ddbd">

2023-10-31 07:45 UTC, simoncozens commented
> Edit: there is a PR fixing this open : https://github.com/notofonts/arabic/pull/207

No, that PR fixes something different - FEE9, rather than 0647.

Khaled's explanation for choice to use a double-eyed form for ہ is [here](https://github.com/notofonts/arabic/pull/199#issuecomment-1705598183):

>  So heh has a different form for final unconnected (the old isolated form) and really isolated (the new one). The single-eye form should only be used after another Arabic letter, and the double-eye is used otherwise (e.g. when heh is shown alone in alphabet charts, or after numbers for Hijri dates, in abbreviations, etc.). This is because the single-eye form looks very close to Arabic Indic 5.

However: the Unicode Standard and code charts use the single-eyed form as "Xn" (isolated):

<img width="784" alt="Screenshot 2023-10-31 at 07 42 15" src="https://github.com/google/fonts/assets/106728/c0df373d-5045-4ba4-9195-3e71c87faa6b">

Which means we seem to have got ahead of Unicode here. @khaledhosny, I think since Noto is an implementation of Unicode, we may need to back out this change.

2023-10-31 15:09 UTC, khaledhosny commented
The [Unicode chart](https://unicode.org/charts/PDF/U0600.pdf) uses this form:
![image](https://github.com/google/fonts/assets/93914/6293178b-659b-481b-a0ca-cf449b32487f)

and the Arabic chapter has this text (though the text is rather misleading, as it is not the initial form but a form very close to it and the initial form is used as a fallback by users):
![image](https://github.com/google/fonts/assets/93914/65800bbb-e77d-4cf5-80b7-f8c11bc63e81)

So there is awareness that isolated heh takes a different form I don’t know why this was not reflected in the table, but this probably would be a 4th column, since heh has 4 forms not 3.

2023-10-31 20:53 UTC, eliheuer commented
I am in favor of using the double-eyed form isolated heh. It is a legibility improvement, it is rendered this way on the Apple keyboards, and I trust Khaled's expertise. This is not a merge blocker from me, and I personally think it is an improvement.

2023-11-07 02:35 UTC, eliheuer requested changes
Almost all the issues I opened in [the upstream git repo](https://github.com/notofonts/arabic/issues) have been closed by [this PR](https://github.com/notofonts/arabic/pull/212) and the one remaining one does not need to be resolved anytime soon: https://github.com/notofonts/arabic/pull/212

There is a commit to the upstream repository fixing the one remaining FontBakery fail: [Update OS/2 usWinAscent for all fonts](https://github.com/notofonts/arabic/pull/212/commits/7f6fb579b598b1fcb0808f5b8fd5c84e1be492c1). @simoncozens can we rebuild the fonts and update this PR with all the new changes? After that this should be ok to merge. Thanks!

2023-11-07 12:21 UTC, eliheuer commented
@simoncozens There are two new FontBakery fails, should they be ignored or fixed?

2023-11-07 12:58 UTC, simoncozens commented
The experimental fail is just... wrong. The second one we have discussed at length and my position remains that if the designer knows what they are doing, using legacy accent glyphs as components of a precomposed glyph is fine. So yes, please ignore both.

2023-11-28 09:58 UTC, eliheuer commented
I reviewed this with Behdad's `fonttools varLib.interpolatable` QA tool: https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/main/reports/NotoSansArabic%5Bwdth%2Cwght%5D.ttf.pdf and all the issues are fixed.

2023-11-28 13:54 UTC, RosaWagner approved these changes

2023-11-28 13:55 UTC, merged

2023-11-28 15:05 UTC, eliheuer reviewed
Looks good!