PPS Article refactored
google/fonts pull request #7027
Opened 2023-11-29 02:51 UTC by vv-monsalve

Hi @chrissimpkins, following what we discussed today, as well as taking one [previous font including an Article as a referent](https://fonts.google.com/specimen/Tiro+Kannada/about), I've rearranged the entire About section to give a better structure doing the following:

- [x] Add the "standard" (less editorial) description at the top of the article.
- [x] Including an `<hr>` element to divide the before from the Article text
- [x] Attempting to add a heading for the Article
- [x] Rearrange the text to move the mention of the Emojis under a subsection dedicated to them
- [x] Adding the list of the available emojis.
- [x] Final round on spell check grammar and turn it into third person.

2023-11-29 02:54 UTC, vv-monsalve commented
@RosaWagner I think #7006 (the PR that is updating the font) should be merged first so this Article update overrides the Article included there.

2023-11-29 04:51 UTC, chrissimpkins requested changes

2023-11-29 04:51 UTC, chrissimpkins commented on ofl/playpensans/article/e-birthday-cake.png
This png is no longer required & should be removed

2023-11-29 04:51 UTC, chrissimpkins commented on ofl/playpensans/article/e-color-palette.png
This png is no longer required & should be removed

2023-11-29 04:51 UTC, chrissimpkins commented on ofl/playpensans/article/e-index-pointing.png
This png is no longer required & should be removed

2023-11-29 04:51 UTC, chrissimpkins commented on ofl/playpensans/article/e-shooting-star.png
This png is no longer required & should be removed

2023-11-29 10:44 UTC, RosaWagner commented on ofl/playpensans/article/e-shooting-star.png
the png are already removed (red minus next to the file path), therefore considering this resolved.

2023-11-29 10:56 UTC, RosaWagner commented
There will be some conflict so I gonna do some little tweaks to the first PR so I can merge this one after.

2023-11-29 11:09 UTC, RosaWagner approved these changes

2023-11-29 11:09 UTC, merged

2023-12-05 16:47 UTC, vv-monsalve commented
I believe this was already stated in my previous comment.

2023-12-05 23:39 UTC, eliheuer commented
Thanks, great example of why reading through everything PR to see what is linked is error prone.