Briem Hand: Version 1.002 added
google/fonts pull request #7040
Opened 2023-11-30 10:31 UTC by simoncozens

4c35df2: [gftools-packager] Briem Hand: Version 1.002 added

* Briem Hand Version 1.002 taken from the upstream repo https://github.com/SorkinType/Briem-Hand.git at commit https://github.com/SorkinType/Briem-Hand/commit/.

2023-11-30 10:56 UTC, emmamarichal commented
Hi @simoncozens, do you need I review it or you're still working on it?

2023-11-30 10:57 UTC, simoncozens commented
Upstream is working on it. :-) I'll try and fix as many of these as I can, some are from the new build process.

2023-11-30 14:06 UTC, emmamarichal commented
- For the font name: I already had this kind of issue, with Darker Grotesque for example: https://fonts.google.com/specimen/Darker+Grotesque  I didn't change the name (the style displayed on the API is the regular), and I ignored the fail. But we can discuss this with the team!
- I can add Gunnlaugur Briem to the catalog
- ⚠ WARN: DESCRIPTION.en_us.html should end in a linebreak. -> Can be avoid, I can do it when all is finished
- ⚠ WARN: Does the font contain a soft hyphen?  Soft Hyphen can be removed from the Glyphset

You can fix the interpolation bugs, here are what I found when I inspected quickly on font gauntlet:

The ogonek should be shifted a bit
<img width="282" alt="Capture d’écran 2023-11-30 à 14 49 44" src="https://github.com/google/fonts/assets/64773544/e011a3d2-db5a-48a4-b914-c5457310b586">

Interpolation issue here (it's maybe already on the list, I didn't check)

https://github.com/google/fonts/assets/64773544/ea840ae6-c3f1-404f-bebf-96ef3081b7ae

The ring seems placed too much on the left

https://github.com/google/fonts/assets/64773544/705fc784-4dc6-4540-abaf-7fd5ccb52a00

2023-11-30 15:16 UTC, simoncozens commented
Interpolation issues:

- [x] downArrow (false positive)
- [x] o.c (false positive, or at least not a visible issue)
- [x] c.a (fixed)
- [x] r.s (fixed)
- [x] section (false positive)
- [x] upArrow (false positive)
- [x] v.c (Fixed)
- [x] z.c (fixed)
- [x] r.c (fixed)
- [ ] o.v
- [x] rtail (fixed)
- [ ] o.z

I think `o.v` and `o.z` are fine but want to confirm with Eben:

<img width="570" alt="Screenshot 2023-11-30 at 15 16 29" src="https://github.com/google/fonts/assets/106728/18fc3c30-b114-493b-8e3b-b6754da2001d">

2023-12-01 09:34 UTC, emmamarichal commented
Hey @simoncozens!

Looks great! 🥳 

Just a few things:

- the A ring is still too far to the left

<img width="273" alt="Capture d’écran 2023-12-01 à 10 10 59" src="https://github.com/google/fonts/assets/64773544/d7fb742f-95d3-4539-afae-b8107f75b9ea">

- The lcaron kerning with 'k' /  and lbar with the 'w'
I don't have any solution, and I imagine it's hard to deal with this kind of things with this design. 
cc @EbenSorkin 

<img width="434" alt="Capture d’écran 2023-12-01 à 10 23 20" src="https://github.com/google/fonts/assets/64773544/f10bb478-5005-4bd3-96cb-22b337aac2e7">

2023-12-01 09:36 UTC, simoncozens commented
Well spotted. I can fix the accents on Aringbelow, kerning will have to be a designer job.

2023-12-05 14:06 UTC, RosaWagner commented
About this FAIL:
🔥 FAIL: METADATA.pb font.name field contains font name in right format? ([com.google.fonts/check/metadata/valid_name_values](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_name_values))
🔥 FAIL METADATA.pb font.name field ("Briem Hand") does not match correct font name format ("Briem Hand Thin"). [code: mismatch]

It is a bug from fontbakery, issue opened here: https://github.com/fonttools/fontbakery/issues/4262. The `font_name` key should be matching the `family name`, not `family name + style name`.

2024-03-27 10:57 UTC, simoncozens commented
Uh, Noto Sans Mongolian fix clearly unrelated. Naughty packager. Let me force-push...

2024-03-27 12:53 UTC, emmamarichal requested changes

2024-03-27 12:53 UTC, emmamarichal commented on ofl/briemhand/METADATA.pb
> +}
should we add `classifications: "HANDWRITING"`?

2024-03-27 12:53 UTC, emmamarichal commented on ofl/briemhand/OFL.txt
> +https://scripts.sil.org/OFL
We should use the new link: `https://openfontlicense.org`

2024-03-27 12:56 UTC, emmamarichal commented
@simoncozens The fontbakery looks good to me.


### Design review:

- There are still some interpolation issues, but I don't think it's visible. But maybe better to fix if you can!
[BriemHand[wght].pdf](https://github.com/google/fonts/files/14773534/BriemHand.wght.pdf)

- This guy (dong) is a bit too far:

<img width="1216" alt="Screenshot 2024-03-27 at 13 43 50" src="https://github.com/google/fonts/assets/64773544/a9418e60-b9ab-434c-837d-e1e1536068e5">

https://github.com/google/fonts/assets/64773544/b575af71-159d-4c26-97f9-2807efac17d4

- Small issue here in the outlines (rupeeIndian):


<img width="491" alt="Screenshot 2024-03-27 at 13 44 15" src="https://github.com/google/fonts/assets/64773544/73e314c6-7c5e-4235-a3da-b03043dbe8a5">

2024-03-27 13:04 UTC, emmamarichal commented
@simoncozens Yes, that's what I thought about the interpolation problems.
But I was thinking that if you fixed the other little problems I mentioned, you could fix the interpolations to avoid a WARN hehe
But it doesn't matter if you don't!

2024-03-27 13:22 UTC, simoncozens commented
I've fixed the dong issue in the repository, I don't feel confident fixing the rupee outlines so that's over to @EbenSorkin.

2024-03-27 15:05 UTC, EbenSorkin commented
I'll see if I can fix this today.

On Wed, Mar 27, 2024 at 9:22 AM Simon Cozens ***@***.***>
wrote:

> I've fixed the dong issue in the repository, I don't feel confident fixing
> the rupee outlines so that's over to @EbenSorkin
> <https://github.com/EbenSorkin>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/fonts/pull/7040#issuecomment-2022752558>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAQUQXKHA57Z27CZ2NXTGZTY2K2YRAVCNFSM6AAAAABAA6F7GKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRSG42TENJVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-27 16:01 UTC, emmamarichal commented on ofl/briemhand/METADATA.pb
> +designer: "Gunnlaugur Briem, Eben Sorkin"
you can add SE to get Gunnlaugur SE Briem

2024-03-27 16:01 UTC, emmamarichal commented on ofl/briemhand/METADATA.pb
> +designer: "Gunnlaugur Briem, Eben Sorkin"
I've updated the designer profile

2024-03-28 07:36 UTC, simoncozens commented
Updated

2024-03-28 07:45 UTC, simoncozens commented
OK, so it was probably a bad time to adjust the axis values... ;-)

2024-03-28 08:37 UTC, simoncozens commented
Updated

2024-03-28 09:03 UTC, emmamarichal commented
@simoncozens 

I have this in the last report: `💥 **ERROR** Familyname must be unique according to namecheck.fontdata.com`
I just updated metadatas and OFL. Any idea? A fontbakery bug?

2024-03-28 09:14 UTC, m4rc1e commented
I think we're making too many requests to namecheck.fontdata.com and we've potentially crashed their server so we should ignore it.

We should be good citizens and only run the check on new families so we need to implement a cache in gb

2024-03-28 09:19 UTC, emmamarichal approved these changes

2024-03-28 09:19 UTC, merged