roboto: change license from apache to ofl
google/fonts pull request #7112
Opened 2023-12-15 09:41 UTC by m4rc1e

This PR takes the static fonts we currently serve, v2.317 and moves them to the ofl dir in order to start the license change process. I took the Roboto static fonts from commit 432ed642284929e50a8ced3f39fcda11a58abf13. This commit predates any of the VF roboto work we've done.

I'll block #6943 not since this PR must come first.

cc @chrissimpkins

2024-01-04 09:24 UTC, emmamarichal commented
@chrissimpkins can I/you merge this PR in order to unblock #6943?

2024-01-04 09:28 UTC, m4rc1e commented
@emmamarichal leave this pr for now. I need to talk to the backend team. We may not need to do anything and this pr will be closed.

2024-01-24 09:31 UTC, emmamarichal requested changes

2024-01-24 09:31 UTC, emmamarichal commented on ofl/roboto/OFL.txt
> +https://scripts.sil.org/OFL
Following https://github.com/google/fonts/issues/7062 the OFL url should be updated to https://openfontlicense.org/

2024-01-24 09:31 UTC, emmamarichal commented on ofl/roboto/METADATA.pb
>  license: "APACHE2"
should be "OFL" right?

2024-01-31 13:39 UTC, emmamarichal commented
@m4rc1e can we close this one, since you open a new one https://github.com/google/fonts/pull/7231 ?

2024-02-09 10:28 UTC, m4rc1e commented
Closing in favour of #7231

2024-02-09 10:28 UTC, closed without merging