Jaini: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
google/fonts pull request #7208
Opened 2024-01-19 15:49 UTC by yanone

b617ba7: [gftools-packager] Jaini: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added

* Jaini Version 2.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/EkType/Jaini at commit https://github.com/EkType/Jaini/commit/c7bc27878832b1f56a7224fdb07100d39503e89f.

2024-01-25 22:41 UTC, vv-monsalve requested changes

2024-01-25 22:41 UTC, vv-monsalve commented on ofl/jaini/DESCRIPTION.en_us.html
> +    particularly referencing a manuscript from 1503 CE. The manuscript style has several unique features not seen in the
@yanone, Same comment as in Jaini Purna: the formatting of the description file looks broken, please adjust it following this https://github.com/fonttools/fontbakery/issues/2811

2024-01-25 22:58 UTC, vv-monsalve commented
I've added a [coment on the similarities between Jaini and Jaini Purva in the font issue](https://github.com/google/fonts/issues/3830#issuecomment-1911127968)

2024-02-08 15:54 UTC, emmamarichal commented
@yanone, same question, could you edit that PR so we can merge it?

2024-02-16 10:36 UTC, yanone commented
Updated

## Jaini: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added

---
 97b1c87: [gftools-packager] Jaini: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added

* Jaini Version 2.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/EkType/Jaini at commit https://github.com/EkType/Jaini/commit/c7bc27878832b1f56a7224fdb07100d39503e89f.

2024-02-16 12:21 UTC, yanone commented
The smart_dropout check isn't supposed to fail. It passes when I run fontbakery with just this check and I investigated the font and found it to be correct. I reported the [issue](https://github.com/fonttools/fontbakery/issues/4525) and ask that this FAIL gets ignored.

2024-03-21 16:52 UTC, yanone commented
I emailed Ektype about filling the categorization form just now.

2024-04-03 13:44 UTC, yanone commented
Still waiting for the categorization by the authors...

2024-04-03 13:58 UTC, emmamarichal commented
status:
these warns should be avoid and updated in sources:
⚠️ **WARN** Check copyright namerecords match license file.
⚠️ **WARN** License URL matches License text on name table?

2024-04-04 10:31 UTC, yanone commented
Updated

2024-04-04 22:29 UTC, vv-monsalve approved these changes

2024-04-04 22:32 UTC, vv-monsalve commented
@yanone I'm merging this here. However, a minisite_url is expected for standard commissioned projects. Please confirm if there is going to be one for the Jaini fonts, and if so, it needs to be included in the `METADATA.pb` file.

2024-04-04 22:32 UTC, merged