Yarndings 20: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
google/fonts pull request #7219
Opened 2024-01-24 13:04 UTC by emmamarichal

16fd506: [gftools-packager] Yarndings 20: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Yarndings 20 Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-yarndings at commit https://github.com/scfried/soft-type-yarndings/commit/200cc40a30ffbe590807cdfc8b8e17d0d63c43ff.

 e59fe9c: description and metadatas updated

2024-02-01 09:36 UTC, emmamarichal commented
@vv-monsalve I updated the description with the sentence about the number.
For the metadatas (subsets), I suggest to let them like this, and try with this PR. If the font is well displayed, we can go ahead with the other PRs. I will let them in draft until we are happy with this one!

2024-02-07 15:16 UTC, vv-monsalve requested changes

2024-02-07 15:16 UTC, vv-monsalve commented on ofl/yarndings20/DESCRIPTION.en_us.html
> +<p>Each typeface has a “Regular” and “Charted” version, and some include multiple scales so you can fit type on your knits, no matter the project's size</p>
The link to the charted version is needed (following the same structure for all the Soft Type fonts)

2024-02-07 15:20 UTC, vv-monsalve commented
> For the metadatas (subsets), I suggest to let them like this, and try with this PR. If the font is well displayed, we can go ahead with the other PRs.

Okay, let's see hoe it perform in Dev.

2024-02-07 16:28 UTC, emmamarichal commented
@vv-monsalve, done :)

2024-02-07 17:26 UTC, vv-monsalve approved these changes

2024-02-07 17:27 UTC, vv-monsalve commented
Excellent! Now we just need to solve the tags issue (!)

2024-02-15 14:06 UTC, merged