update push lists
google/fonts pull request #7345
Opened 2024-03-04 13:39 UTC by m4rc1e

2024-03-04 16:00 UTC, m4rc1e commented
Setting to draft since I'll add a few more goodies.

2024-03-06 10:46 UTC, emmamarichal approved these changes

2024-03-06 16:11 UTC, chrissimpkins requested changes

2024-03-06 16:11 UTC, chrissimpkins commented on to_sandbox.txt
>  # Deleted: lang/languages/sa_Sylo.textproto # https://github.com/google/fonts/pull/7248
Let's add the latest categorization tagging data to the main branch csv file and the csv file path to the to_sandbox list before we merge the lists this week.

@emmamarichal @m4rc1e

2024-03-06 16:18 UTC, emmamarichal commented
> Let's add the latest categorization tagging data to the main branch csv file and the csv file path to the to_sandbox list before we merge the lists this week.
> 
> @emmamarichal @m4rc1e


-> I added it, @m4rc1e please correct me if it's not the good way to add it!

2024-03-06 16:25 UTC, chrissimpkins commented
> > Let's add the latest categorization tagging data to the main branch csv file and the csv file path to the to_sandbox list before we merge the lists this week.
> > @emmamarichal @m4rc1e
> 
> -> I added it, @m4rc1e please correct me if it's not the good way to add it!

Will need the data update in the csv file too

2024-03-06 19:16 UTC, chrissimpkins commented
We'll need to define Workspace menu families for some Jacquard families.  The design does not show up well in the menus:

![5fnkuer5ZBUTfDQ](https://github.com/google/fonts/assets/4249591/201b762e-08e3-4369-87ce-8e5b93a8a7fc)

Going through the full list and will let you know which ones we will need to remove from the to_production list until we make this change.

2024-03-06 19:29 UTC, chrissimpkins requested changes

2024-03-06 19:29 UTC, chrissimpkins commented on to_production.txt
> +ofl/jacquard12charted # https://github.com/google/fonts/pull/7300
let's remove this line

2024-03-06 19:29 UTC, chrissimpkins commented on to_production.txt
> +ofl/jacquard12 # https://github.com/google/fonts/pull/7152
let's remove this line

2024-03-06 19:29 UTC, chrissimpkins commented on to_production.txt
> +ofl/jacquardabastarda9charted # https://github.com/google/fonts/pull/7084
let's remove this line

2024-03-06 19:31 UTC, chrissimpkins commented
> We'll need to define Workspace menu families for some Jacquard families. The design does not show up well in the menus:
> 
> ![jacquard](https://private-user-images.githubusercontent.com/4249591/310635210-d60d6ea9-1c5d-4a5b-9bd9-6abcabf1c18f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTM2NjMsIm5iZiI6MTcwOTc1MzM2MywicGF0aCI6Ii80MjQ5NTkxLzMxMDYzNTIxMC1kNjBkNmVhOS0xYzVkLTRhNWItOWJkOS02YWJjYWJmMWMxOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTkyOTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNlMWJmMTkwNTYyMWEyNDQ1NjkwYzQ2OWYwMTA0NmQwMjA1ZGJjMjdkYmY5ZjRkMDRmZDBkMjY3NjhlNGU0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hMOrXe9RWziIQYhJm1qQRDN6tnfgQhjr7APiH4aoU30)
> 
> Going through the full list and will let you know which ones we will need to remove from the to_production list until we make this change.

This involves all of the Jacquard families.  Let's remove all of them from the to_prod list this week and I will work on the definition of the menu families for Workspace. I think that we should be able to move them into production next week. We'll do the same confirmation with the next list prep to confirm that they are gtg.

I can confirm that all of the Yarndings families are ready following the changes that we made in recent weeks.  OK to ship all of those to prod.

I tested all of the other new families in the list and they are also ready to go.  Jacquard families are the only ones that require a change before we merge this.

2024-03-07 08:59 UTC, emmamarichal commented
@chrissimpkins For now, I blocked all the charted families, except Yarndings. I wait for your confirmation before remove them from the list.
How does Jacquarda Bastarada 9 Charted appear for example?

<img width="1317" alt="Screenshot 2024-03-07 at 09 58 01" src="https://github.com/google/fonts/assets/64773544/f5efbef2-0163-42f9-a159-093af87c3890">

2024-03-07 16:22 UTC, m4rc1e commented
Family tags have been merged, https://github.com/google/fonts/pull/7370.

cc @chrissimpkins @emmamarichal

2024-03-08 14:58 UTC, chrissimpkins commented
CSV data updated and Jacquard families were removed as we work on the internal changes necessary to support a Workspace font selection menu alternate.  Ready to merge here.

2024-03-12 10:35 UTC, merged