Lists of the 29th of March
google/fonts pull request #7501
Opened 2024-03-29 14:00 UTC by emmamarichal

@chrissimpkins 

- there are a lot of Soft Type project that reached the sandbox and are now in the to_production list. I guess there are some menus rendering to check here

2024-03-29 18:44 UTC, chrissimpkins commented
Have we re-pushed Noto CJK families to sandbox so that we re-subset and Simon can look into https://github.com/google/fonts/issues/6024#issuecomment-2025615505?

2024-04-02 17:38 UTC, chrissimpkins requested changes
We're merging Workspace editor menu families for the Jersey and Jacquard families listed here.  Let's wait on that to land to merge the to_production list.

2024-04-02 21:58 UTC, chrissimpkins requested changes

2024-04-02 21:58 UTC, chrissimpkins commented on to_sandbox.txt
> +ofl/ojuju # https://github.com/google/fonts/pull/7333
The Ojuju metadata update is in sandbox.  Let's remove https://github.com/google/fonts/pull/7333 from to_sandbox and add it to to_production. Thanks!

2024-04-03 07:29 UTC, emmamarichal commented
@chrissimpkins done!

2024-04-03 21:38 UTC, chrissimpkins commented
Menu families look good.  Let's open a new PR to address https://github.com/google/fonts/pull/7501#issuecomment-2027596686.  I'll merge this one.

2024-04-03 21:38 UTC, chrissimpkins approved these changes

2024-04-03 21:38 UTC, merged