Freeman: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
google/fonts pull request #7548
Opened 2024-04-12 02:59 UTC by vv-monsalve

Taken from the upstream repo https://github.com/rfuenzalida/Freeman/master at commit https://github.com/rfuenzalida/Freeman/master/commit/5ced8a95f5b0e0c3dcea3b033398ba93a56fb687.

Resolves #3121
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

2024-04-12 03:20 UTC, vv-monsalve commented
Hi @emmamarichal 
- 🔥 **FAIL** Check tabular widths don't have kerning.
    This appears to be a false Fail. The font doesn't have the reported kernings
- 🔥 **FAIL** Shapes languages in all GF glyphsets.
    Per private conversation it was agreed to publish the font as is for this v1.000
- Designer bio for Aoife will be added later

2024-04-12 08:47 UTC, emmamarichal requested changes

2024-04-12 08:47 UTC, emmamarichal commented on ofl/freeman/OFL.txt
> +https://scripts.sil.org/OFL
url to update

2024-04-12 08:48 UTC, emmamarichal commented
@vv-monsalve 
`Designer bio for Aoife will be added later`
-> She already has one, so we are good for designers profiles :)

2024-04-12 16:33 UTC, vv-monsalve commented on ofl/freeman/OFL.txt
> +https://scripts.sil.org/OFL
Solved.

2024-04-17 07:46 UTC, emmamarichal approved these changes

2024-04-17 07:46 UTC, merged