push lists and tags updated
google/fonts pull request #7604
Opened 2024-04-26 16:19 UTC by m4rc1e

2024-04-26 19:18 UTC, chrissimpkins requested changes
Jacquard 25 Charted and Jersey 25 Charted require Workspace menu families.  I'll work with the Fonts eng team to land this before we merge these updates.  Should be by early next week.

2024-04-26 19:18 UTC, chrissimpkins commented on to_production.txt
> +ofl/jacquard24charted # https://github.com/google/fonts/pull/7525
Requires a Workspace menu family.

2024-04-26 19:18 UTC, chrissimpkins commented on to_production.txt
> +ofl/jersey25charted # https://github.com/google/fonts/pull/7536
Requires a Workspace menu family

2024-04-26 19:24 UTC, chrissimpkins commented
> Jacquard 24 Charted and Jersey 25 Charted require Workspace menu families. I'll work with the Fonts eng team to land this before we merge these updates. Should be by early next week.

Changes opened and review requested from Nate.

2024-04-27 18:44 UTC, chrissimpkins commented
CI is failing on Knowledge HTML tag checks

2024-04-29 18:55 UTC, chrissimpkins commented
This should remain open? Or are you preparing a new set of lists?

2024-04-29 19:19 UTC, chrissimpkins commented on to_production.txt
> +ofl/jacquard24charted # https://github.com/google/fonts/pull/7525
We continue to wait on the menu family update.  Not ready to merge yet.

2024-04-29 19:20 UTC, chrissimpkins commented on to_production.txt
> +ofl/jersey25charted # https://github.com/google/fonts/pull/7536
We continue to wait on the menu family update.  Not ready to merge yet.

2024-04-29 19:51 UTC, m4rc1e commented
Sorry, Github automatically closed this PR when I merged #7613

2024-04-30 15:50 UTC, chrissimpkins commented on to_production.txt
> +ofl/jacquard24charted # https://github.com/google/fonts/pull/7525
The menu family is updated in sandbox.  All clear here

2024-04-30 15:50 UTC, chrissimpkins commented on to_production.txt
> +ofl/jersey25charted # https://github.com/google/fonts/pull/7536
The menu family is updated in sandbox. All clear here

2024-04-30 15:51 UTC, chrissimpkins commented
All set for merge from my standpoint.

2024-05-01 11:07 UTC, merged