Chocolate Classical Sans: Version 1.001 added
google/fonts pull request #7664
Opened 2024-05-15 05:12 UTC by aaronbell

Taken from the upstream repo https://github.com/aaronbell/ChocolateSans at commit https://github.com/aaronbell/ChocolateSans/commit/ce0c3c542b943f1e56fddc54116f1c18326f5ba1.

2024-05-15 05:14 UTC, aaronbell commented
The maintainer of the upstream repro is not responsive to my PR, so am submitting from my local repository. There are existing FAILS that have been reviewed with @chrissimpkins, but if there's any issues let's discuss!

2024-05-15 13:34 UTC, emmamarichal requested changes

2024-05-15 13:34 UTC, emmamarichal commented on ofl/chocolateclassicalsans/DESCRIPTION.en_us.html
> +"Chocolate Classical Sans" is an open source font suitable for Traditional Chinese environments. It is based on the "Source Sans" font jointly developed by Adobe and Google. It partially refers to he
Add the "To contribute" part, like <p>To contribute, see <a href="https://github.com/fontrepo/fontname">github.com/fontrepo/fontname</a>.</p>

2024-05-15 13:34 UTC, emmamarichal commented on ofl/chocolateclassicalsans/OFL.txt
> +https://scripts.sil.org/OFL
url to change (see Cactus)

2024-05-15 14:01 UTC, emmamarichal commented
### **Part II: Outlines / Spacing**

- I didn't asked for Cactus, but are we happy with this kind of spacing?
<img width="1618" alt="Screenshot 2024-05-15 at 15 46 39" src="https://github.com/google/fonts/assets/64773544/26b7903e-6bd1-43da-ac4b-4ab632b59003">

______

- A some small issue in spacing: it concerns /uni20DD/uni20DE
<img width="219" alt="Screenshot 2024-05-15 at 15 54 54" src="https://github.com/google/fonts/assets/64773544/9d30423b-17b6-4f76-8f2a-d01a3a1a7f6d">

2024-05-15 18:20 UTC, aaronbell commented
> 🔥 FAIL Shapes languages in all GF glyphsets. vi_Latn (Vietnamese) Some mark glyphs were missing: ◌̃, ◌̉, ◌̛, ◌̣ -> This is the only marks missing, could we solve this to avoid the fail?

Done
> 
> 🔥 FAIL Ensure files are not too large. -> I suppose that's inevitable for a CJK font

Yup...

> 🔥 FAIL Check Google Fonts glyph coverage. -> Can you confirm that it's ok and agreed the font doesn't cover the Latin Core glyphset?

Confirmed. Latin Kernel is sufficient!

> ⚠️ WARN Are there caret positions declared for every ligature? -> Don't know how ligatures are made in CJK. Is it possible to solve this? We don't have it in Cactus.

The only ligatures that I'm seeing in the font are Latin ones for `fl`, `fi`, and `ffi`. Cactus doesn't have any `liga` substitutions because Chocolate Sans is based on Source Han Sans, so it has different capabilites. I don't think this is anything we need to worry about.

2024-05-15 18:26 UTC, aaronbell commented
> ### **Part II: Outlines / Spacing**
> 
>     * I didn't asked for Cactus, but are we happy with this kind of spacing?

This is fine. TC punctuation works differently than we expect, so the centered positionings are fine. 

For 20DD and 20DE, these are enclosing glyphs, meant to be positioned over the previous glyph, so I think it is OK for these to be as they are.

2024-05-15 18:32 UTC, aaronbell commented
Updated

2024-05-15 19:11 UTC, hfhchan commented on ofl/chocolateclassicalsans/DESCRIPTION.en_us.html
> +<p>"Chocolate Classical Sans" is an open source font suitable for Traditional Chinese environments. It is based on the "Source Sans" font jointly developed by Adobe and Google. It partially refers to
```suggestion
<p>"Chocolate Classical Sans" is an open source font suitable for Traditional Chinese environments. This font uses inherited glyphs, largely adhering to the <i>Inherited Glyphs standard</i> maintained by the <i>I.Font Project</i>, combined with other commonly seen inherited glyphs, to produce a Chinese typeface with glyphs in the traditional style.</p>.

<p>This font is produced by Tian Haidong, with modifications from Moonlit Owen.</p>

<p>This font is based on the "Source Han Sans" font jointly developed by Adobe and Google, incorporating modifications and additional glyphs by using open source contributions from Steve Yuu, GuiWonder and ChiuMing.</p>
```

2024-05-15 19:11 UTC, hfhchan commented on ofl/chocolateclassicalsans/DESCRIPTION.en_us.html
> +<p>"Chocolate Classical Sans" is an open source font suitable for Traditional Chinese environments. It is based on the "Source Sans" font jointly developed by Adobe and Google. It partially refers to
(To confirm Tian's preferred transliteration of his name.)

2024-05-16 08:31 UTC, emmamarichal commented
@hfhchan, I commited your changes, I propose we go ahead, and we will add modifications if they are needed :)

2024-05-16 08:33 UTC, emmamarichal commented
@hfhchan should we add Tian Haidong in the designers list for this font? (in the metadatas and specimen)

2024-05-16 08:35 UTC, emmamarichal approved these changes

2024-05-16 12:23 UTC, emmamarichal commented
I merge it, the changes are about metadatas, we can still update them later! let's move on!

2024-05-16 12:27 UTC, aaronbell commented
> @aaronbell 🔥 FAIL METADATA.pb: Check URL on copyright string is the same as in repository_url field. We should update this then, by adding the same url everywhere!

I'm not sure if it makes sense to put my repro name in the copyright string when the upstream owner it MoonlitOwen, but I also think that it makes sense to preserve my repro name as the location of this particular version of the font since it is different than MoonlitOwen's. Thoughts?

2024-05-16 12:30 UTC, emmamarichal commented
Ok, then I merge it, and I will notify my colleagues. If there are any issues with that, we will update it.
thanks!

2024-05-16 12:30 UTC, merged

2024-05-16 18:41 UTC, hfhchan commented
> @hfhchan should we add Tian Haidong in the designers list for this font? (in the metadatas and specimen)

Yes but I have yet to receive a reply from them about the preferred transliteration.

> This is fine. TC punctuation works differently than we expect, so the centered positionings are fine.

Yes, I can confirm TC punctuation is always supposed to be in the middle.