Lang v062
google/fonts pull request #7877
Opened 2024-06-21 16:16 UTC by emmamarichal

solves Chinese specimen issue

2024-06-24 16:33 UTC, nathan-williams requested changes

2024-06-24 16:33 UTC, nathan-williams commented on lang/Lib/gflanguages/data/languages/gan_Hant.textproto
> +>>>>>>> f6a234f61ded3f2c386870192ad701f47105c23b
Looks like a bad merge. Please fix.

2024-06-24 16:33 UTC, nathan-williams commented on lang/Lib/gflanguages/data/languages/hsn_Hant.textproto
> +<<<<<<< HEAD
Please resolve merge diffs.

2024-06-24 16:33 UTC, nathan-williams commented on lang/Lib/gflanguages/data/languages/wuu_Hant.textproto
> +<<<<<<< HEAD
""

2024-06-25 08:04 UTC, emmamarichal commented
@nathan-williams, done! you can merge it. (It seems I can't merge it myself)

2024-06-25 09:12 UTC, m4rc1e approved these changes

2024-06-25 09:12 UTC, merged