Update pushlists
google/fonts pull request #8354
Opened 2024-10-18 15:14 UTC by m4rc1e

cc @chrissimpkins

2024-10-23 15:12 UTC, chrissimpkins requested changes

2024-10-23 15:12 UTC, chrissimpkins commented on to_production.txt
> +ofl/notoserifhentaigana # https://github.com/google/fonts/pull/7327
There was an issue with primary_script in sandbox.  I think that we might still need to solve this issue before the prod push?

@simoncozens to confirm that this is not meant as a fix for the issue in the production push here?

2024-10-23 15:13 UTC, chrissimpkins commented on to_production.txt
> +ofl/notoserifhentaigana # https://github.com/google/fonts/pull/7327
cc @nathan-williams

2024-10-23 15:15 UTC, chrissimpkins commented on to_production.txt
> +ofl/notoserifhentaigana # https://github.com/google/fonts/pull/7327
Let's remove the Noto Serif Hentatigana family from the to_prod list for now so that we can continue to move the other families.  Ty!

2024-10-24 08:57 UTC, emmamarichal approved these changes

2024-10-24 09:05 UTC, merged